# This is how we install NGINX with docker so we use
# it in the app
server {
    listen 80;
    server name clothingpredict.com;

    location / {
        # this points ngnix to the python app
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}